### ISSUE TITLE
Parameter 'path' seems to be non-optional

### ISSUE THREAD

**Issue by Luuk34** [gngrninja/PSFolderSize#1]
If I leave out the paramater '-Path', the command seems to 'hang'
example:
`Get-FolderSize -output csv -Outputpath c:\temp`
'hangs', CTRL+C is use to stop it...

but this works:
`Get-FolderSize -Path . -output csv -Outputpath c:\temp`

CORRECTION: Above statement does not 'hang', but description in help is wrong.
Help states 'The basePath parameter defaults to C:\Users.'
(line#12 in PSFolderSize.psm1, vs line#22 in the same file)

An improvement would be to allow:
`Get-FolderSize -output csv c:\temp\output.csv`
or 
`Get-FolderSize -output c:\temp\output.csv`

These last 2 command should not give output on screen, but just output stuff to the give filename.

**Comment by Luuk34** [comment]
I just solve my own problem, by changing line #136 (of PSFolerSize.psm1) to:
`$BasePath = (Get-Location).Path`

This will make basePath default to the current directory, which I like 👍

**Comment by gngrninja** [comment]
The BasePath parameter of the script is used to determine where it starts getting the folder sizes from. Is that what you like defaulting to the current location? 

As for the -Output and then a path, I would like to keep different output types incorporated (csv, xml, and json), so breaking it out makes sense. Perhaps I could see if OutputPath is a path that exists, and then if there also is a file name try to use that to determine the output type.

**Comment by Luuk34** [comment]
Yes, I would like that the default starting location is set to the current location.

For the "-Output & -OutputPath" options, i'm more into an "-OutputFile" option.
Some examples:
-OutputFile c:\temp\output.csv   . create a csv-file, named output.csv in c:\temp\
-OutputFile c:\temp\output.xml   . create a xml-file, named output.xml in c:\temp\
....
-OutputFile output.csv   . create a csv-file, named output.csv in the current location.

With your options above first example would look like:
-Output csv -OutputPath c:\temp
Problem with this is that the output-file has a RANDOM name, and cannot be use in other scripts (because the name is random, i.e. '040718_1957.csv')

**Comment by gngrninja** [comment]
The default for the output outputs a file with a timestamp, so some regex matching and parsing would indeed have to be done. I will add an option that allows -OutputFile as you placed above, and place them in a different parameter set than -Output and -OutputPath. Thanks for the feedback!

**Comment by gngrninja** [comment]
@Luuk34 Check out this branch: https://github.com/gngrninja/PSFolderSize/tree/issue/basepathandoutput

I changed the following:

- Set the path as the default parameter by setting it as position zero
- Changed the path for folder size lookup and outputting results to default to (Get-Location)
- Added -OutputFile, which will attempt to see which format via the extension (.json, .xml, and .csv)

Let me know if that works for you!

**Comment by Luuk34** [comment]
PS C:\temp> $PSVErsionTable

Name                           Value
----                           -----
PSVersion                      5.1.16299.251
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.16299.251
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1


PS C:\temp> import-module C:\util\PSFolderSize
PS C:\temp> Get-FolderSize
Get-FolderSize : Parameter set cannot be resolved using the specified named parameters.
At line:1 char:1
+ Get-FolderSize
+ ~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Get-FolderSize], ParameterBindingException
    + FullyQualifiedErrorId : AmbiguousParameterSet,Get-FolderSize

PS C:\temp> Get-FolderSize -Path c:\util
Get-FolderSize : Parameter set cannot be resolved using the specified named parameters.
At line:1 char:1
+ Get-FolderSize -Path c:\util
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Get-FolderSize], ParameterBindingException
    + FullyQualifiedErrorId : AmbiguousParameterSet,Get-FolderSize

PS C:\temp> Get-FolderSize -Path c:\temp
Get-FolderSize : Parameter set cannot be resolved using the specified named parameters.
At line:1 char:1
+ Get-FolderSize -Path c:\temp
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Get-FolderSize], ParameterBindingException
    + FullyQualifiedErrorId : AmbiguousParameterSet,Get-FolderSize

PS C:\temp> module

ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Manifest   3.1.0.0    Microsoft.PowerShell.Management     {Add-Computer, Add-Content, Checkpoint-Computer, Clear-Con...
Manifest   3.1.0.0    Microsoft.PowerShell.Utility        {Add-Member, Add-Type, Clear-Variable, Compare-Object...}
Binary     1.0.0.1    PackageManagement                   {Find-Package, Find-PackageProvider, Get-Package, Get-Pack...
Script     1.0.0.1    PowerShellGet                       {Find-Command, Find-DscResource, Find-Module, Find-RoleCap...
Script     1.0        PSFolderSize                        Get-FolderSize
Script     1.2        PSReadline                          {Get-PSReadlineKeyHandler, Get-PSReadlineOption, Remove-PS...


PS C:\temp>

**Comment by gngrninja** [comment]
Check out the latest version of https://github.com/gngrninja/PSFolderSize/tree/issue/basepathandoutput now! I will be doing some more testing, but so far so good.

**Comment by gngrninja** [comment]
Did more testing, working on PowerShell v5.0 and pwsh core. Let me know if you have any other questions/issues!
