### ISSUE TITLE
Use PSFolderSize on Remote machine?

### ISSUE THREAD

**Issue by gilneas79** [gngrninja/PSFolderSize#11]
Is there a way to use PSFoldersize on a remote machine? Very new to powershell scripting.

**Comment by gngrninja** [comment]
If you have access to the remote machine as a share, you could run it as such:
`Get-FolderSize \\192.168.1.15\c$`

I would look into some of the PowerShell remoting basics, here: https://docs.microsoft.com/en-us/powershell/scripting/learn/remoting/running-remote-commands?view=powershell-6.

Once you have an understanding of remoting, and you have the module installed on the remote machine, you can use a PSSession and/or Invoke-Command to run it.
