### ISSUE TITLE
Leveraging the Size(GB) parameter doesn't work with PSCustomObject

### ISSUE THREAD

**Issue by k00laidIT** [gngrninja/PSFolderSize#13]
There doesn't seem to be any version of wrapping the Size(GB)|(MB)|(KB)|(Bytes) parameters when used in an array that you can then feed it into a custom object without it choking on the parenthesis in the parameter. Could you possibly change the parameter names to sizeGB, sizeMB, etc.?

Example: 
$remotefolders = Get-FolderSize -BasePath $unc -OmitFolders $omitFolder

    foreach ($remotefolder in $remotefolders) {        

        $folderObj = New-Object PSObject -Property @{
            folderName  = $remotefolder.folderName
            #folderSizeGB    = $remotefolder.Size(GB)
        }

**Comment by gngrninja** [comment]
You could get this working by surrounding the property name in quotes, as such:
`folderSizeGB    = $remotefolder.'Size(GB)'`

Either way, I have changed the property names in the next release to make things easier and less confusing. Look for the update today.
