### ISSUE TITLE
Gets all folders, not the one specified

### ISSUE THREAD

**Issue by SiggeSigvardsson** [gngrninja/PSFolderSize#14]
$basepath = "c:\ApplicationFolder\"
$folder = "Data"
The command: "$Usage = Get-foldersize -basepath $BasePath -foldername $Folder"

This gives me the information for; Data, Data1, Data2 and so on. I´m reading the help file, but as far as i can tell it should give me only the specified folder.

**Comment by SiggeSigvardsson** [comment]
Just to be clear, i worked around it using:
"$Usage | where {$_.Foldername -like $Folder}"
So not a a big issue.

**Comment by gngrninja** [comment]
This is because it is matching on folders that match 'data'. You can do further filtering after, as you have done. I can change this if it is confusing.
