### ISSUE TITLE
Output sorting

### ISSUE THREAD

**Issue by d3solath** [gngrninja/PSFolderSize#15]
Would love to get possibility to sort with another -output parameter by specified column, e.g. "-OutputSort FolderName".
"Sort-Object 'FolderName' " only effects the PS output, not the *.csv

**Comment by gngrninja** [comment]
I will look into getting this added, great idea!

**Comment by gngrninja** [comment]
This should be available now: https://github.com/gngrninja/PSFolderSize/releases/tag/v1.7.0

Test it out and let me know what you think.

**Comment by d3solath** [comment]
Thanks a lot! Even when I'm confused by trying around here.
So, now the Output method does only work when OutpuSort is given. If not, you're getting errors ("method not supported").
With "-Output csv -OutputSort FolderName" you'll get ascending output (z-a), even if source reads "Descending".
Tried to rewrite the code from 'Descending' to 'Ascending' and re-import without any impact.
