### ISSUE TITLE
Question: -AddTotal Results in Different Columns

### ISSUE THREAD

**Issue by rpstester** [gngrninja/PSFolderSize#18]
Hi, I like your script so far. I have a question/confusion.  I'm on Windows PowerShell 5.1

If I run Get-FolderSize -BasePath c:\users\myself\downloads, then I get four columns: FolderName, SizeMB, SizeGB, and FullPath. 
However, if I run the same and add the -AddTotal switch, then suddenly, I get more columns: FolderName, SizeBytes, SizeKB, SizeMB, SizeGB, FullPath, and HostName.  (I also see the total line at the top.)

Is there a reason that "AddTotal" is returning more data fields/properties?

Using Get-Member, it looks like "AddTotal" is returning a "PsCustomObject" as well the other "PS.Folder.List.Result" objects.  
Perhaps if the GrandTotal is in the same object format, then there won't be surprise extra results.

Let me know what you think and if I can be of service to make a change.

**Comment by gngrninja** [comment]
This may be due to the formatting I have applied by default. You should be able to see all of those fields with either command if you pipe the results to | Select *, aye?

**Comment by gngrninja** [comment]
Can you test out the latest merge to master, and see if it is good now?

**Comment by rpstester** [comment]
Looks much nicer. Thank you!
P.S. Is there anything I can do for your project for the sake of Hacktoberfest?

**Comment by gngrninja** [comment]
Not off the top of my head, but if I think of anything, I'll let you know!
