### ISSUE TITLE
Syntax help

### ISSUE THREAD

**Issue by paulharman** [gngrninja/PSFolderSize#31]
Hi,

I am trying to get the summary details of any folders named chrome* (e.g. chrome_data, chrome_downloads).  How do I do this please? I seem to get file details when all I want is folder size and file count.

Thanks

**Comment by gngrninja** [comment]
You could do something like this:
```
$results = Get-FolderSize -Path 'path/to/your/folders'

$results | Where-Object {$_.Name -match '^chrome.+}
```

Does that make sense?
