### ISSUE TITLE
OmitFolder - Using Wildcards to omit random file names or others.

### ISSUE THREAD

**Issue by cengbrecht** [gngrninja/PSFolderSize#33]
Hello!

First, thanks for the awesome tool. 
Second, this works excellently for almost everything I use it for. 

The issue I am running into is that when I am filtering my folder list I am seeing folders and files I don't want to list or, maybe don't care about. 
I don't know if this is a supported case as I could not find it, but I wanted to ask. 

In the examples below, I wanted to filter out the $ folders `ie. C:\$6B9E02DFCC9A4DF7BD9798A64F1E0D85` as well as \*.sys, or others, but I was testing $* first.

My query:
`PS C:\WINDOWS\system32> Get-FolderSize -Path 'C:\' -OmitFolders 'C:\Temp','C:\Windows','C:\Workspace','C:\Users','$*' | Where-Object {$_.'Size(MB)' -ne 'Empty'}`

The wildcard part:
**`,'$*'`**

The Output: (Works great just not filtered)
```
FolderName                     SizeMB       SizeGB       FullPath
----------                     ------       ------       --------
Autodesk                       31168.63     30.44        C:\Autodesk
... Truncated ...
Config.Msi                     4.8          0            C:\Config.Msi
$6B9E02DFCC9A4DF7BD9798A64F1E0 3.31         0            C:\$6B9E02DFCC9A4DF7BD9798A64F1E0D85
$C4D3D31086214879B0EB6F6FB7896 3.31         0            C:\$C4D3D31086214879B0EB6F6FB78961F4
Intel                          1.13         0            C:\Intel
$Windows.~WS                   0.34         0            C:\$Windows.~WS
... Truncated ...
System Volume Information                                C:\System Volume Information
```

What I had hoped to see:
```
FolderName                     SizeMB       SizeGB       FullPath
----------                     ------       ------       --------
Autodesk                       31168.63     30.44        C:\Autodesk
... Truncated ...
Config.Msi                     4.8          0            C:\Config.Msi
Intel                          1.13         0            C:\Intel
$Windows.~WS                   0.34         0            C:\$Windows.~WS
... Truncated ...
System Volume Information                                C:\System Volume Information
```

**Comment by cengbrecht** [comment]
Also, on that.... Autodesk is DUMB for how much space they waste on drives with their "installation" files...

**Comment by gngrninja** [comment]
Seems like it is a waste, including all those files. 
I will be taking a look at this next week once I wrap up a work project. 

Thanks for the feedback and details!

**Comment by gngrninja** [comment]
Currently, OmitFolders is meant to take the full paths of folders you want to omit. 

I will see about adding a parameter that can filter based on wildcards/names as well.
