### ISSUE TITLE
Getting error with Update-TypeData

### ISSUE THREAD

**Issue by erikcurtis** [gngrninja/PSFolderSize#4]
**When I do:**
$csv = Import-Csv p:\ComputersAndUsers.csv
foreach ($line in $csv) {
    Get-FolderSize -BasePath $line.FullPath -FolderName $line.FolderName
}

**I get the folder size but also:**
Update-TypeData : Error in TypeData "PS.Folder.List.Result": The member DefaultDisplayPropertySet is already present.
At P:\PowershellScripts\PSFolderSize\PSFolderSize\PSFolderSize.psm1:342 char:5

**Comment by gngrninja** [comment]
I merged in some changes I have been working on. Give it a try now. @erikcurtis #6

**Comment by gngrninja** [comment]
Closing this out as it should have been resolved. Can no longer reproduce.
