### ISSUE TITLE
DE number formatting

### ISSUE THREAD

**Issue by gngrninja** [gngrninja/PSFolderSize#7]
From PS Gallery comment:

> I was getting an error with DE number format where decimals are ',' separator. TT.CCC,DD, so I had to edit the .ps1 files and remove the [double] cast added in the version 1.5 
> 
> In any case, thanks for the script, it was really helpful!

**Comment by Masterxilo** [comment]
Same issue here

```
Der Wert "1’840.63" kann nicht in den Typ "System.Double" konvertiert werden. Fehler: "Die Eingabezeichenfolge hat das falsche Format."
In C:\Program Files\WindowsPowerShell\Modules\PSFolderSize\1.5\Public\Get-FolderSize.ps1:224 Zeichen:9
+         [double]$folderSizeInMB = "{0:N2}" -f ($folderSize.Sum / 1MB)
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : MetadataError: (:) [], ArgumentTransformationMetadataException
    + FullyQualifiedErrorId : RuntimeException
```

**Comment by gngrninja** [comment]
Thanks for the report, working on getting this fixed in the next commit.

**Comment by gngrninja** [comment]
This has been fixed @Masterxilo - check out the latest version in the gallery by using Update-Module PSFolderSize. You can also try manually importing the file if you clone/download the repo. # #
