### ISSUE TITLE
i know, i should not use filename with square brackets......

### ISSUE THREAD

**Issue by Luuk34** [gngrninja/PSFolderSize#8]
PS C:\temp> Get-FolderSize C:\TEmp\lala*.*
Get-ChildItem : Cannot retrieve the dynamic parameters for the cmdlet. The specified wildcard character pattern is not
valid: lala[].txt
At C:\Program Files\WindowsPowerShell\Modules\PSFolderSize\1.6.2\Functions\Public\Get-FolderSize.ps1:216 char:23
+ ... olderSize = Get-Childitem -Path $fullPath -Recurse -Force -ErrorActio ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Get-ChildItem], ParameterBindingException
    + FullyQualifiedErrorId : GetDynamicParametersException,Microsoft.PowerShell.Commands.GetChildItemCommand

FolderName                     Size(MB)     Size(GB)     FullPath
----------                     --------     --------     --------
lala                           0,00         0,00         C:\TEmp\lala.txt
lala4e                         0,00         0,00         C:\TEmp\lala4e.txt
lala4                          0,00         0,00         C:\TEmp\lala4.txt
lala                           0,00         0,00         C:\TEmp\lala.zip
lala8                          0,00         0,00         C:\TEmp\lala8.txt
lala                           0,00         0,00         C:\temp\lala.txt~
lala10                         0,00         0,00         C:\TEmp\lala10.txt
lala5                          0,00         0,00         C:\TEmp\lala5.txt
lala[]                         0,00         0,00         C:\TEmp\lala[].txt

PS C:\temp>

**Comment by gngrninja** [comment]
Nope! This one was totally on me. I updated the code to use a different parameter when looking for folders. Please try:

```powershell
Update-Module PSFolderSize, close and re-open PowerShell, then try again.
```

You can also try downloading the latest build here and importing it that way.

**Comment by Luuk34** [comment]
Actually i'm doing something 'wrong' here too.

I'm trying to filer on filenames in a folder, and Get-FolderSize does not seem to do this.

**So, this fails:**
```
PS C:\temp> Get-FolderSize C:\Temp\lala*.*
Get-ChildItem : Cannot find path 'C:\Temp\lala*.*' because it does not exist.
At C:\Program Files\WindowsPowerShell\Modules\PSFolderSize\1.6.3\Functions\Private\Get-FolderList.ps1:29 char:23
+         $allFolders = Get-ChildItem -LiteralPath $BasePath -Force |
+                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Temp\lala*.*:String) [Get-ChildItem], ItemNotFoundException
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.GetChildItemCommand
```

**but I should do this**
```
PS C:\temp> Get-FolderSize C:\Temp\  | where foldername -like 'lala*'

FolderName                     Size(MB)     Size(GB)     FullPath
----------                     --------     --------     --------
lala                           0,00         0,00         C:\Temp\lala.txt
lala4e                         0,00         0,00         C:\Temp\lala4e.txt
lala4                          0,00         0,00         C:\Temp\lala4.txt
lala                           0,00         0,00         C:\Temp\lala.zip
lala8                          0,00         0,00         C:\Temp\lala8.txt
lala                           0,00         0,00         C:\Temp\lala.txt~
lala10                         0,00         0,00         C:\Temp\lala10.txt
lala[]                         0,00         0,00         C:\Temp\lala[].txt
lala5                          0,00         0,00         C:\Temp\lala5.txt
```

**Comment by gngrninja** [comment]
I'll see about adding something like that in a future release! Going to close out the main issue for now. Thanks for the feedback.
